project_id = "ismwvaoprkarsmfgkhpc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_parameter_status = "off"

[realtime]
enabled = true
ip_version = "ipv6"
tenant_id = "realtime-dev"
token = "your-secret-jwt-token-with-at-least-32-characters-long"
max_header_length = 4096

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge_functions]
enabled = true

[functions.create-batch]
verify_jwt = true

[functions.get-batches]
verify_jwt = false

[functions.buy-batch]
verify_jwt = true

[functions.sell-to-retailer]
verify_jwt = true

[functions.create-order]
verify_jwt = true

[functions.get-trace]
verify_jwt = false