// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ismwvaoprkarsmfgkhpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzbXd2YW9wcmthcnNtZmdraHBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MTMzOTksImV4cCI6MjA2OTA4OTM5OX0.U2MqiLW-m26JfD3PYXSYCEDrjHTzKmSqfO0sNIgzvlM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});